---
driver:
  name: terraform

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      attrs_outputs:
        client_sofia: public_dns_clients_sofia
        server_sofia: public_dns_servers_sofia
        client_varna: public_dns_clients_varna
        server_varna: public_dns_servers_varna

platforms:
  - name: terraform

suites:
  - name: default
